runtime: python39  # Replace with your desired Python runtime (e.g., python38, python310)

entrypoint: gunicorn -b :$PORT school.wsgi

instance_class: F2

env_variables:
  DJANGO_SETTINGS_MODULE: "school.settings"
  TWILIO_ACCOUNT_SID: your-account-sid
  TWILIO_AUTH_TOKEN: your-auth-token
  TWILIO_NUMBER: your-twilio-number

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
# Routing for static files
- url: /static
  static_dir: static/

# Routing for Django app
- url: /.*
  script: auto

libraries:
- name: MySQLdb
  version: 1.2.5
-name: django_countries
version: 7.5.1
