runtime: python310 

entrypoint: gunicorn -b :$PORT school.wsgi  

instance_class: F2  

env_variables:
  APPENGINE_URL: 'https://school-exam-analysis-system.appspot.com'
  DJANGO_SETTINGS_MODULE: "school.settings"
  DEBUG: "False"
  EMAIL_HOST_USER: "emailschoolkenya@gmail.com"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_USE_TLS: "True"
  EMAIL_HOST_PASSWORD: "m34sopAn!"
  TWILIO_ACCOUNT_SID: "ACddde302eddb819a1110c07fdcc043b8e"
  TWILIO_AUTH_TOKEN: "b03741d3bdb553a7b8d87d7922e090b8"
  TWILIO_PHONE_NUMBER: "+13343452538"
  ENGINE: "django.db.backends.mysql"
  DATABASE_URL: "mysql://root:m34sopAn!@/cloudsql/school-exam-analysis-system:us-central1/schooldeb/schooldb"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  # Routing for static files
  - url: /static
    static_dir: static/

  # Routing for Django app
  - url: /.*
    script: auto
 